"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import raw from "./interventions-data.json";

type Attachment={id:string;name:string;url:string;type:string};
type Row={id:string;apartment:string;date:string;category:string;description:string;author:string;status?:string;attachments?:Attachment[]};
type View="dashboard"|"interventions"|"apartments"|"reports";
const CATEGORY_RULES:[string,RegExp][]=[
 ["Équipement bébé",/lit\s*(?:bb|bébé|bebe)|chaise\s*haute|équipement\s*(?:bb|bébé|bebe)/i],
 ["Nuisibles & hygiène",/fourmi|cafard|insecte|nid\s|guêpe|guepe|pigeon|odeur|moisi|moisiss|sale|hygiène|hygiene/i],
 ["Textile & rideaux",/rideau|tringle|barre\s+rideau|drap|couette|oreiller|housse|serviette|textile/i],
 ["Électroménager & TV",/frigo|réfrig|refrig|four|micro.?onde|plaque|lave.?vaisselle|télé|tele|\btv\b|téléphone|telephone|cafeti|machine\s+[àa]\s+caf[ée]|grille.?pain|bouilloire/i],
 ["Électricité & clim",/clim|climat|chauffage|radiateur|électri|electri|lumière|lumiere|ampoule|prise|interrupteur|ventilateur|disjonct|détecteur|detecteur/i],
 ["Menuiserie & accès",/porte|fenêtre|fenetre|baie|serrure|poignée|poignee|store|volet|clé|cle\s|placard|charnière|charniere|vitre/i],
 ["Plomberie",/fuite|douche|baignoire|lavabo|[ée]vier|\bwc\b|toilette|chasse|robinet|eau\s|évacuation|evacuation|bouch[ée]|pommeau|siphon|bonde/i],
 ["Mobilier & literie",/chaise|table|canapé|canape|\blit\b|sommier|matelas|surmatelas|meuble|pied\s|poubelle|tancarville|tank?arville|étagère|etagere|étendoir|etendoir/i],
];
const FOLLOW_UP_ONLY=/vous me confirm|tu me confirm|on peut rien faire|vous pouvez y aller|donc il est parti|\bmerci\b|remerci/i;
const TECHNICAL_DETAIL=/vibration|alarme|incendie|néon|neon|freezer|marbre|fissur|accoudoir|d[ée]bo[iî]t|dysjonct|disjonct|sonne|retirer|récupérer|recuperer|ventilo|barre|planche|travaux?|intervention/i;
function isHousekeepingStatus(text:string){const value=text.replace(/\b\d{1,3}\b/g," ").replace(/[\/,;&+.:–—-]/g," ").replace(/\b(?:et|l|appartement|appart|appt)\b/gi," ").replace(/\s+/g," ").trim();return /^(?:propre|nickel|ok|ras|fait|réglé|regle|résolu|resolu|libre|bon|tout bon)$/i.test(value)}
const isCountableText=(text:string)=>!isHousekeepingStatus(text)&&(!FOLLOW_UP_ONLY.test(text)||CATEGORY_RULES.some(([,rule])=>rule.test(text))||TECHNICAL_DETAIL.test(text));
const normalizeApartmentNumber=(value:string)=>{const number=Number.parseInt(value,10);return Number.isInteger(number)&&number>=1&&number<=999?String(number).padStart(3,"0"):value};
const normalizeCategory=(text:string,current:string)=>CATEGORY_RULES.find(([,rule])=>rule.test(text))?.[0]||current||"Autre technique";
function cleanDescription(text:string,apartment:string,category:string){
 let value=text.replace(/[\r\n]+/g," ").replace(/\s+/g," ").trim();
 const apartmentPattern=[apartment,String(Number.parseInt(apartment,10))].filter((item,index,list)=>item&&list.indexOf(item)===index).join("|");
 value=value.replace(new RegExp(`\\b(?:${apartmentPattern})\\b\\s*[:–—-]?`,"gi")," ")
  .replace(/\b(?:stp|svp|s'il vous plaît|si possible)\b/gi," ")
  .replace(/\best[ -]?il possible de\b/gi," ")
  .replace(/\bsdb\b/gi,"salle de bain").replace(/\bhs\b/gi,"hors service")
  .replace(/\bbb\b/gi,"bébé").replace(/\bfrigo\b/gi,"réfrigérateur")
  .replace(/\bclim\b/gi,"climatisation").replace(/\btv\b/gi,"télévision")
  .replace(/\b(?:tancarville|tankarville)\b/gi,"étendoir").replace(/\b(?:ne\s+)?marche pas\b/gi,"ne fonctionne pas")
  .replace(/\ba changer\b/gi,"à changer")
  .replace(/\ba refaire\b/gi,"à refaire").replace(/\bdeposer\b/gi,"déposer").replace(/machine a café/gi,"machine à café")
  .replace(/^[A-ZÀ-Ÿ0-9' ]{8,}/,part=>part.toLocaleLowerCase("fr-FR")).replace(/\bd4(?=[a-zà-ÿ])/gi,"d'")
  .replace(/\s*\/{2,}\s*/g," · ").replace(/\s+/g," ").replace(/^[\s:;,./+–—-]+|[\s:;,./+–—-]+$/g,"").trim();
 if(!(value.match(/[A-Za-zÀ-ÿ]{4,}/g)||[]).length)return `${category} · intervention à préciser`;
 if(value===value.toLocaleUpperCase("fr-FR")&&/[A-ZÀ-Ÿ]{4}/.test(value))value=value.toLocaleLowerCase("fr-FR");
 return value.charAt(0).toUpperCase()+value.slice(1);
}
function normalizeRow(row:Row):Row{const apartment=normalizeApartmentNumber(row.apartment);const category=normalizeCategory(row.description,row.category);return {...row,apartment,category,description:cleanDescription(row.description,apartment,category)}}
const isPreciseRow=(row:Row)=>!row.description.endsWith("· intervention à préciser");
function deduplicateRows(rows:Row[]){const unique=new Map<string,Row>();for(const row of rows){const sourceId=row.id.replace(/-\d{1,3}$/,"");const key=`${sourceId}|${row.apartment}`;const existing=unique.get(key);unique.set(key,existing?{...existing,...row,status:row.status||existing.status,attachments:row.attachments?.length?row.attachments:existing.attachments}:row)}return [...unique.values()].sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime())}
const fallbackData=deduplicateRows((raw as Row[]).filter(row=>isCountableText(row.description)).map(normalizeRow).filter(isPreciseRow));
const TOTAL_APARTMENTS=260;
const monthFmt=new Intl.DateTimeFormat("fr-FR",{month:"long",year:"numeric",timeZone:"Europe/Paris"});
const shortMonthFmt=new Intl.DateTimeFormat("fr-FR",{month:"short",timeZone:"Europe/Paris"});
const dayFmt=new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"short",year:"numeric",timeZone:"Europe/Paris"});
const timeFmt=new Intl.DateTimeFormat("fr-FR",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Paris"});
const monthKey=(date:string)=>date.slice(0,7);
const monthLabel=(month:string)=>monthFmt.format(new Date(`${month}-15T12:00:00Z`));
const colorClass=(category:string)=>({"Plomberie":"blue","Plomberie et sanitaires":"blue","Électricité & clim":"amber","Électricité et éclairage":"amber","Climatisation et chauffage":"cyan","Menuiserie & accès":"cyan","Menuiserie et accès":"cyan","Textile & rideaux":"green","Stores et rideaux":"green","Électroménager & TV":"violet","Électroménager et cuisine":"violet","TV, téléphone et Internet":"violet","Mobilier & literie":"rose","Mobilier et literie":"rose","Nuisibles & hygiène":"red","Nuisibles, odeurs et hygiène":"red","Équipement bébé":"mint"}[category]||"slate");
const statusClass=(status:string)=>status.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replaceAll(" ","-");
const priority=(row:Row)=>!row.status||row.status==="Terminée"?"Normale":row.status==="Urgente"||/urgent|danger|fuite importante|inond|plus d.eau|plus de courant/i.test(row.description)?"Urgente":row.status==="En attente"?"À surveiller":"Normale";
const STATUS_RANK:Record<string,number>={"Urgente":0,"Signalée":1,"En cours":2,"En attente":3,"Terminée":4,"Archivée":5};
const rowRank=(row:Row)=>STATUS_RANK[row.status||"Archivée"]??6;

function Sidebar({view,setView,live}:{view:View;setView:(view:View)=>void;live:boolean}){
 const items:[View,string,string][]=[["dashboard","▦","Tableau de bord"],["interventions","≡","Interventions"],["apartments","⌂","Appartements"],["reports","▥","Rapports"]];
 return <aside className="crm-sidebar no-print"><div className="crm-brand"><b>MG</b><span><strong>Mer & Golf</strong><small>Port Argelès</small></span></div><nav>{items.map(([id,icon,label])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><i>{icon}</i>{label}</button>)}</nav><div className="sidebar-foot"><span className={live?"live":""}><i/>{live?"Pumble connecté":"Archive locale"}</span><small>Service technique</small></div></aside>
}

function StatusBadge({status="Archivée"}:{status?:string}){return <span className={`status-badge ${statusClass(status)}`}>{status}</span>}

function SeasonPrint({rows,period,category}:{rows:Row[];period:string;category:string}){
 const categorySummary=[...new Set(rows.map(row=>row.category))].map(name=>({name,count:rows.filter(row=>row.category===name).length})).sort((a,b)=>b.count-a.count);
 const apartmentSummary=[...new Set(rows.map(row=>row.apartment))].map(number=>{const items=rows.filter(row=>row.apartment===number);return {number,count:items.length,last:items[0]?.date,categories:[...new Set(items.map(row=>row.category))]}}).sort((a,b)=>b.count-a.count||a.number.localeCompare(b.number));
 const monthlySummary=[...new Set(rows.map(row=>monthKey(row.date)))].sort().map(month=>{const items=rows.filter(row=>monthKey(row.date)===month);return {month,count:items.length,apartments:new Set(items.map(row=>row.apartment)).size}});
 const busiestMonth=[...monthlySummary].sort((a,b)=>b.count-a.count)[0];
 const recurrences=apartmentSummary.flatMap(apartment=>apartment.categories.map(name=>({apartment:apartment.number,name,count:rows.filter(row=>row.apartment===apartment.number&&row.category===name).length}))).filter(item=>item.count>=2).sort((a,b)=>b.count-a.count).slice(0,15);
 const title=period==="all"?"Bilan de la saison":monthLabel(period);
 return <section className="print-only season-print print-report">
  <header className="print-title"><div><small>MER & GOLF · SERVICE TECHNIQUE</small><h1>Rapport de maintenance</h1><p>{title}{category!=="all"?` · ${category}`:" · Toutes les catégories"}</p></div><b>{rows.length}<span>interventions</span></b></header>
  <div className="print-kpis"><article><small>APPARTEMENTS CONCERNÉS</small><strong>{apartmentSummary.length}</strong><span>sur {TOTAL_APARTMENTS}</span></article><article><small>MOYENNE / LOGEMENT</small><strong>{apartmentSummary.length?(rows.length/apartmentSummary.length).toFixed(1):"0"}</strong><span>interventions</span></article><article><small>CATÉGORIE PRINCIPALE</small><strong>{categorySummary[0]?.name||"—"}</strong><span>{categorySummary[0]?.count||0} cas</span></article><article><small>MOIS LE PLUS ACTIF</small><strong>{busiestMonth?monthLabel(busiestMonth.month):"—"}</strong><span>{busiestMonth?.count||0} interventions</span></article></div>
  <div className="print-columns"><section><h2>Répartition par catégorie</h2><table><thead><tr><th>Catégorie</th><th>Nombre</th><th>Part</th></tr></thead><tbody>{categorySummary.map(item=><tr key={item.name}><td>{item.name}</td><td>{item.count}</td><td>{Math.round(item.count/Math.max(rows.length,1)*100)} %</td></tr>)}</tbody></table></section><section><h2>Activité mensuelle</h2><table><thead><tr><th>Mois</th><th>Interventions</th><th>Logements</th><th>Moyenne</th></tr></thead><tbody>{monthlySummary.map(item=><tr key={item.month}><td>{monthLabel(item.month)}</td><td>{item.count}</td><td>{item.apartments}</td><td>{(item.count/Math.max(item.apartments,1)).toFixed(1)}</td></tr>)}</tbody></table></section></div>
  <div className="print-columns"><section><h2>Appartements les plus sollicités</h2><table><thead><tr><th>N°</th><th>Interventions</th><th>Catégories</th><th>Dernière</th></tr></thead><tbody>{apartmentSummary.slice(0,15).map(item=><tr key={item.number}><td><b>{item.number}</b></td><td>{item.count}</td><td>{item.categories.join(" · ")}</td><td>{item.last?dayFmt.format(new Date(item.last)):"—"}</td></tr>)}</tbody></table></section><section><h2>Récurrences à contrôler</h2>{recurrences.length?<table><thead><tr><th>Appartement</th><th>Catégorie répétée</th><th>Occurrences</th></tr></thead><tbody>{recurrences.map(item=><tr key={`${item.apartment}-${item.name}`}><td><b>{item.apartment}</b></td><td>{item.name}</td><td>{item.count}</td></tr>)}</tbody></table>:<p className="print-empty">Aucune catégorie répétée sur la période.</p>}</section></div>
  <section className="print-page-break"><h2>Détail chronologique des interventions</h2><table><thead><tr><th>Date</th><th>Appartement</th><th>Catégorie</th><th>Intervention</th><th>Statut</th><th>Signalé par</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{dayFmt.format(new Date(row.date))}</td><td><b>{row.apartment}</b></td><td>{row.category}</td><td>{row.description}</td><td>{row.status||"Archivée"}</td><td>{row.author}</td></tr>)}</tbody></table></section>
 </section>
}

function ApartmentPrint({number,rows}:{number:string;rows:Row[]}){
 const ordered=[...rows].sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime());
 const categories=[...new Set(ordered.map(row=>row.category))].map(name=>({name,count:ordered.filter(row=>row.category===name).length})).sort((a,b)=>b.count-a.count);
 const months=[...new Set(ordered.map(row=>monthKey(row.date)))].sort().map(month=>({month,count:ordered.filter(row=>monthKey(row.date)===month).length}));
 const repeated=categories.filter(item=>item.count>=2);
 const attachmentCount=ordered.reduce((total,row)=>total+(row.attachments?.length||0),0);
 return <section className="print-only apartment-print print-report">
  <header className="print-title"><div><small>MER & GOLF · FICHE TECHNIQUE SAISONNIÈRE</small><h1>Appartement N° {number}</h1><p>Historique complet de maintenance</p></div><b>{ordered.length}<span>interventions</span></b></header>
  <div className="print-kpis apartment-kpis"><article><small>DERNIÈRE INTERVENTION</small><strong>{ordered[0]?dayFmt.format(new Date(ordered[0].date)):"—"}</strong><span>{ordered[0]?.category||"Aucune donnée"}</span></article><article><small>PREMIÈRE INTERVENTION</small><strong>{ordered.at(-1)?dayFmt.format(new Date(ordered.at(-1)!.date)):"—"}</strong><span>début de l’historique</span></article><article><small>CATÉGORIE PRINCIPALE</small><strong>{categories[0]?.name||"—"}</strong><span>{categories[0]?.count||0} cas</span></article><article><small>MOIS ACTIFS</small><strong>{months.length}</strong><span>{attachmentCount} pièce{attachmentCount>1?"s":""} jointe{attachmentCount>1?"s":""}</span></article></div>
  {repeated.length>0&&<aside className="print-alert"><strong>Points à contrôler à l’intersaison</strong><p>{repeated.map(item=>`${item.name} : ${item.count} occurrences`).join(" · ")}. Ces récurrences méritent un contrôle préventif avant la prochaine saison.</p></aside>}
  <div className="print-columns"><section><h2>Catégories rencontrées</h2><table><thead><tr><th>Catégorie</th><th>Nombre</th><th>Part</th></tr></thead><tbody>{categories.map(item=><tr key={item.name}><td>{item.name}</td><td>{item.count}</td><td>{Math.round(item.count/Math.max(ordered.length,1)*100)} %</td></tr>)}</tbody></table></section><section><h2>Répartition mensuelle</h2><table><thead><tr><th>Mois</th><th>Interventions</th></tr></thead><tbody>{months.map(item=><tr key={item.month}><td>{monthLabel(item.month)}</td><td>{item.count}</td></tr>)}</tbody></table></section></div>
  <section className="print-page-break"><h2>Historique chronologique complet</h2><table><thead><tr><th>Date</th><th>Catégorie</th><th>Intervention</th><th>Statut</th><th>Signalé par</th><th>Pièces jointes</th></tr></thead><tbody>{ordered.map(row=><tr key={row.id}><td>{dayFmt.format(new Date(row.date))}</td><td>{row.category}</td><td>{row.description}</td><td>{row.status||"Archivée"}</td><td>{row.author}</td><td>{row.attachments?.length||0}</td></tr>)}</tbody></table></section>
 </section>
}

export default function Page(){
 const [data,setData]=useState<Row[]>(fallbackData); const [view,setView]=useState<View>("dashboard"); const [period,setPeriod]=useState("all"); const [query,setQuery]=useState(""); const [category,setCategory]=useState("all"); const [status,setStatus]=useState("all"); const [selected,setSelected]=useState<string|null>(null); const [printApartment,setPrintApartment]=useState<string|null>(null); const [syncing,setSyncing]=useState(false); const [live,setLive]=useState(false); const [syncedAt,setSyncedAt]=useState<string|null>(null); const [syncError,setSyncError]=useState("");
 const sync=useCallback(async()=>{setSyncing(true);setSyncError("");try{const response=await fetch("/api/pumble",{cache:"no-store"});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||"Erreur Pumble");if(!Array.isArray(result.rows)||!result.rows.length)throw new Error("Aucune intervention trouvée dans ce canal");setData(current=>{const incoming=result.rows.filter((row:Row)=>isCountableText(row.description)).map(normalizeRow).filter(isPreciseRow);return deduplicateRows([...current,...incoming])});setLive(true);setSyncedAt(result.syncedAt)}catch(error){setSyncError(error instanceof Error?error.message:"Erreur Pumble")}finally{setSyncing(false)}},[]);
 useEffect(()=>{sync()},[sync]);
 useEffect(()=>{const resetPrint=()=>setPrintApartment(null);window.addEventListener("afterprint",resetPrint);return()=>window.removeEventListener("afterprint",resetPrint)},[]);
 const months=useMemo(()=>[...new Set(data.map(row=>monthKey(row.date)))].sort().reverse(),[data]);
 const categories=useMemo(()=>[...new Set(data.map(row=>row.category))].sort(),[data]);
 const periodRows=useMemo(()=>period==="all"?data:data.filter(row=>monthKey(row.date)===period),[data,period]);
 const referenceDate=new Date(data[0]?.date||"2026-08-20T12:00:00Z").getTime();
 const rows=useMemo(()=>periodRows.filter(row=>(!query||row.apartment.includes(query)||row.description.toLowerCase().includes(query.toLowerCase()))&&(category==="all"||row.category===category)&&(status==="all"||(row.status||"Archivée")===status)).sort((a,b)=>rowRank(a)-rowRank(b)||new Date(b.date).getTime()-new Date(a.date).getTime()),[periodRows,query,category,status]);
 const apartmentMap=useMemo(()=>{const map=new Map<string,Row[]>();periodRows.forEach(row=>map.set(row.apartment,[...(map.get(row.apartment)||[]),row]));return [...map].map(([number,items])=>({number,items,total:items.length,latest:items[0],categories:[...new Set(items.map(item=>item.category))]})).sort((a,b)=>b.total-a.total||a.number.localeCompare(b.number))},[periodRows]);
 const categoryCounts=useMemo(()=>categories.map(name=>({name,count:periodRows.filter(row=>row.category===name).length})).filter(item=>item.count).sort((a,b)=>b.count-a.count),[periodRows,categories]);
 const statusCounts=useMemo(()=>["Urgente","En cours","En attente","Signalée","Terminée","Archivée"].map(name=>({name,count:periodRows.filter(row=>(row.status||"Archivée")===name).length})),[periodRows]);
 const monthsTrend=useMemo(()=>[...months].reverse().map(month=>({month,count:data.filter(row=>monthKey(row.date)===month).length,apartments:new Set(data.filter(row=>monthKey(row.date)===month).map(row=>row.apartment)).size})),[months,data]);
 const reportRows=useMemo(()=>periodRows.filter(row=>category==="all"||row.category===category),[periodRows,category]);
 const reportCategoryCounts=useMemo(()=>[...new Set(reportRows.map(row=>row.category))].map(name=>({name,count:reportRows.filter(row=>row.category===name).length})).sort((a,b)=>b.count-a.count),[reportRows]);
 const reportStatusCounts=useMemo(()=>["Urgente","En cours","En attente","Signalée","Terminée","Archivée"].map(name=>({name,count:reportRows.filter(row=>(row.status||"Archivée")===name).length})),[reportRows]);
 const reportMonthsTrend=useMemo(()=>[...new Set(reportRows.map(row=>monthKey(row.date)))].sort().map(month=>{const items=reportRows.filter(row=>monthKey(row.date)===month);return {month,count:items.length,apartments:new Set(items.map(row=>row.apartment)).size}}),[reportRows]);
 const reportApartmentCount=new Set(reportRows.map(row=>row.apartment)).size;
 const maxTrend=Math.max(...monthsTrend.map(item=>item.count),1); const recurrent=apartmentMap.filter(apartment=>apartment.total>=4); const selectedRows=selected?data.filter(row=>row.apartment===selected):[]; const selectedCategoryCounts=[...new Set(selectedRows.map(row=>row.category))].map(name=>({name,count:selectedRows.filter(row=>row.category===name).length})).sort((a,b)=>b.count-a.count); const recurrentProblems=selectedCategoryCounts.filter(item=>item.count>=2); const selectedFiles=selectedRows.flatMap(row=>(row.attachments||[]).map(file=>({...file,date:row.date})));
 function openApartment(number:string){setSelected(number)}
 function triggerPrint(apartment?:string){setPrintApartment(apartment||null);requestAnimationFrame(()=>requestAnimationFrame(()=>window.print()))}
 return <div className={`crm-shell ${printApartment?"printing-apartment":"printing-report"}`}><Sidebar view={view} setView={setView} live={live}/><main className="crm-main"><header className="crm-topbar no-print"><div><h1>{view==="dashboard"?"Tableau de bord":view==="interventions"?"Interventions":view==="apartments"?"Appartements":"Rapports"}</h1><p>{period==="all"?"Saison entière":monthLabel(period)}</p></div><label className="global-search"><span>⌕</span><input aria-label="Recherche globale" placeholder="Appartement ou problème…" value={query} onChange={event=>setQuery(event.target.value)}/></label><select aria-label="Période" value={period} onChange={event=>setPeriod(event.target.value)}><option value="all">Saison entière</option>{months.map(month=><option key={month} value={month}>{monthLabel(month)}</option>)}</select><button className="sync-action" disabled={syncing} onClick={sync}>{syncing?"Synchronisation…":"Actualiser Pumble"}</button><button className="avatar">FT</button></header>{syncError&&<div className="sync-warning no-print">{syncError} · Les données archivées restent affichées.</div>}
 {view==="dashboard"&&<section className="crm-view dashboard-view"><div className="welcome season-total"><div><small>{period==="all"?"BILAN DE LA SAISON":"BILAN MENSUEL"}</small><h2>{periodRows.length} intervention{periodRows.length!==1?"s":""}</h2><p>{apartmentMap.length} appartement{apartmentMap.length!==1?"s":""} concerné{apartmentMap.length!==1?"s":""} · {live?`Pumble synchronisé${syncedAt?` à ${timeFmt.format(new Date(syncedAt))}`:""}`:"Données archivées"}</p></div><button onClick={()=>setView("reports")}>Consulter le bilan détaillé <span>→</span></button></div><div className="dashboard-grid season-dashboard-grid"><article className="crm-card category-card"><div className="card-head"><div><h3>Catégories principales</h3><p>Répartition des {periodRows.length} interventions</p></div></div><div className="category-bars">{categoryCounts.slice(0,7).map(item=><div key={item.name}><span><i className={colorClass(item.name)}/>{item.name}<b>{item.count}</b></span><progress max={categoryCounts[0]?.count||1} value={item.count}/></div>)}</div></article><article className="crm-card activity-card"><div className="card-head"><div><h3>Activité mensuelle</h3><p>Interventions et logements concernés</p></div></div><div className="modern-chart">{monthsTrend.map(item=><div key={item.month}><b>{item.count}</b><span><i style={{height:`${Math.max(item.count/maxTrend*100,5)}%`}}/></span><strong>{shortMonthFmt.format(new Date(`${item.month}-15T12:00:00Z`))}</strong><small>{item.apartments} apt.</small></div>)}</div></article><article className="crm-card recurrent-card"><div className="card-head"><div><h3>Appartements les plus sollicités</h3><p>Classement sur la période</p></div><button onClick={()=>setView("apartments")}>Voir le parc</button></div><div>{apartmentMap.slice(0,6).map((apartment,index)=><button key={apartment.number} onClick={()=>openApartment(apartment.number)}><i>{index+1}</i><span><strong>Appartement {apartment.number}</strong><small>{apartment.categories.slice(0,2).join(" · ")}</small></span><b>{apartment.total}</b></button>)}</div></article></div></section>}
 {view==="interventions"&&<section className="crm-view"><div className="view-toolbar"><div className="quick-filters"><button className={status==="all"?"active":""} onClick={()=>setStatus("all")}>Toutes <b>{periodRows.length}</b></button>{statusCounts.map(item=><button key={item.name} className={status===item.name?"active":""} onClick={()=>setStatus(item.name)}>{item.name} <b>{item.count}</b></button>)}</div><select aria-label="Catégorie" value={category} onChange={event=>setCategory(event.target.value)}><option value="all">Toutes les catégories</option>{categories.map(name=><option key={name}>{name}</option>)}</select></div><article className="crm-card table-card"><div className="card-head"><div><h3>Liste des interventions</h3><p>{rows.length} résultat{rows.length>1?"s":""}</p></div></div><div className="crm-table"><div className="table-row table-header"><span>Appartement</span><span>Intervention</span><span>Catégorie</span><span>Priorité</span><span>Statut</span><span>Signalée</span></div>{rows.map(row=><button className="table-row" key={row.id} onClick={()=>openApartment(row.apartment)}><span><b className="apt-number">{row.apartment}</b></span><span><strong>{row.description}</strong><small>{row.author}</small></span><span><i className={`category-dot ${colorClass(row.category)}`}/>{row.category}</span><span><em className={`priority ${priority(row).toLowerCase().replace(" ","-")}`}>{priority(row)}</em></span><span><StatusBadge status={row.status}/></span><span><b>{dayFmt.format(new Date(row.date))}</b><small>{Math.max(0,Math.floor((referenceDate-new Date(row.date).getTime())/3600000))} h</small></span></button>)}</div></article></section>}
 {view==="apartments"&&<section className="crm-view"><div className="apartment-overview"><article><small>APPARTEMENTS SUIVIS</small><strong>{apartmentMap.length}</strong><span>sur {TOTAL_APARTMENTS}</span></article><article><small>SANS INTERVENTION</small><strong>{TOTAL_APARTMENTS-apartmentMap.length}</strong><span>sur la période</span></article><article><small>À SURVEILLER</small><strong>{recurrent.length}</strong><span>4 interventions ou plus</span></article><article><small>LE PLUS SOLLICITÉ</small><strong>N° {apartmentMap[0]?.number||"—"}</strong><span>{apartmentMap[0]?.total||0} interventions</span></article></div><div className="apartment-grid">{apartmentMap.filter(apartment=>!query||apartment.number.includes(query)||apartment.latest.description.toLowerCase().includes(query.toLowerCase())).map(apartment=><button key={apartment.number} onClick={()=>openApartment(apartment.number)}><div><b>{apartment.number}</b><StatusBadge status={apartment.latest.status}/></div><h3>Appartement {apartment.number}</h3><p>{apartment.latest.description}</p><span><small>{apartment.total} intervention{apartment.total>1?"s":""}</small><em>{apartment.categories[0]}</em></span>{apartment.total>=4&&<i className="watch-flag">À surveiller</i>}</button>)}</div></section>}
 {view==="reports"&&<section className="crm-view"><div className="report-head"><div><small>RAPPORT DE MAINTENANCE</small><h2>{period==="all"?"Bilan de la saison":monthLabel(period)}</h2><p>{reportRows.length} interventions · {reportApartmentCount} appartements concernés{category!=="all"?` · ${category}`:""}</p></div><div className="report-actions"><select aria-label="Catégorie du rapport" value={category} onChange={event=>setCategory(event.target.value)}><option value="all">Toutes les catégories</option>{categories.map(name=><option key={name}>{name}</option>)}</select><button onClick={()=>triggerPrint()}>Imprimer le rapport</button></div></div><div className="report-grid"><article className="crm-card"><div className="card-head"><div><h3>Répartition par catégorie</h3><p>Types d’intervention les plus fréquents</p></div></div><div className="report-categories">{reportCategoryCounts.map((item,index)=><div key={item.name}><b>{index+1}</b><span><strong>{item.name}</strong><progress max={reportCategoryCounts[0]?.count||1} value={item.count}/></span><em>{item.count}</em><small>{Math.round(item.count/Math.max(reportRows.length,1)*100)} %</small></div>)}</div></article><article className="crm-card"><div className="card-head"><div><h3>Statuts</h3><p>État des interventions Pumble</p></div></div><div className="status-report">{reportStatusCounts.map(item=><div key={item.name}><StatusBadge status={item.name}/><strong>{item.count}</strong><small>{Math.round(item.count/Math.max(reportRows.length,1)*100)} %</small></div>)}</div></article><article className="crm-card monthly-report"><div className="card-head"><div><h3>Évolution mensuelle</h3><p>Comparaison sur la sélection</p></div></div><table><thead><tr><th>Mois</th><th>Interventions</th><th>Appartements</th><th>Moyenne / logement</th></tr></thead><tbody>{reportMonthsTrend.map(item=><tr key={item.month}><td>{monthLabel(item.month)}</td><td>{item.count}</td><td>{item.apartments}</td><td>{(item.count/Math.max(item.apartments,1)).toFixed(1)}</td></tr>)}</tbody></table></article></div></section>}
 <SeasonPrint rows={reportRows} period={period} category={category}/>{printApartment&&<ApartmentPrint number={printApartment} rows={data.filter(row=>row.apartment===printApartment)}/>}</main>
 {selected&&<div className="overlay no-print" onMouseDown={()=>setSelected(null)}><aside className="drawer" onMouseDown={event=>event.stopPropagation()}><header><div><small>FICHE APPARTEMENT · SAISON ENTIÈRE</small><h2>N° {selected}</h2><p>{selectedRows.length} intervention{selectedRows.length>1?"s":""} · dernière le {selectedRows[0]?dayFmt.format(new Date(selectedRows[0].date)):"—"}</p></div><div className="drawer-actions"><button className="drawer-print" onClick={()=>triggerPrint(selected)}>Imprimer la fiche</button><button className="drawer-close" aria-label="Fermer" onClick={()=>setSelected(null)}>×</button></div></header><section className="apt-summary"><div><small>STATUT ACTUEL</small><StatusBadge status={selectedRows[0]?.status}/></div><div><small>INTERVENTIONS SAISON</small><strong>{selectedRows.length}</strong></div><div><small>CATÉGORIE PRINCIPALE</small><strong>{selectedCategoryCounts[0]?.name||"—"}</strong></div></section>{recurrentProblems.length>0&&<div className="recurrence-warning"><b>Problème récurrent détecté</b><p>{recurrentProblems.slice(0,3).map(item=>`${item.name} (${item.count})`).join(" · ")}</p></div>}<section className="dominant-categories"><small>CATÉGORIES LES PLUS FRÉQUENTES</small><div>{selectedCategoryCounts.slice(0,4).map(item=><span key={item.name}><i className={colorClass(item.name)}/>{item.name}<b>{item.count}</b></span>)}</div></section>{selectedFiles.length>0&&<section className="attachments"><small>PHOTOS ET PIÈCES JOINTES PUMBLE</small><div>{selectedFiles.slice(0,8).map(file=><a key={file.id} href={file.url} target="_blank" rel="noreferrer"><b>{/image/i.test(file.type)?"Photo":"Fichier"}</b><span>{file.name}</span><time>{dayFmt.format(new Date(file.date))}</time></a>)}</div></section>}<div className="history"><h3>Historique chronologique</h3>{selectedRows.map(row=><article key={row.id}><i className={colorClass(row.category)}/><div><time>{dayFmt.format(new Date(row.date))}</time><b>{row.category}</b><StatusBadge status={row.status}/><p>{row.description}</p><small>Signalé par {row.author}{(row.attachments?.length||0)>0?` · ${row.attachments!.length} pièce(s) jointe(s)`:""}</small></div></article>)}</div></aside></div>}</div>
}
